// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kezbdbbeqocqtdxyhtqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlemJkYmJlcW9jcXRkeHlodHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTgyNzEsImV4cCI6MjA3NDI5NDI3MX0.mT583yli0GeugzDA_c2f6rJmJ2_NKgifF95TeFSOtho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});